import{a as w,S as b,i as a}from"./assets/vendor-D0cagnvz.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();function m(r,e,s){const l="https://pixabay.com/api/",t={key:s,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e},o=new URLSearchParams(t).toString(),n=`${l}?${o}`;return w.get(n)}function p(r){return r.map(e=>`
      <a href="${e.largeImageURL}" class="gallery-link">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        <ul class="image-info">
          <li>Likes <span>${e.likes}</span></li>
          <li>Views <span>${e.views}</span></li>
          <li>Comments <span>${e.comments}</span></li>
          <li>Downloads <span>${e.downloads}</span></li>
        </ul>
      </a>`).join("")}const u=document.querySelector("#search-form"),f=document.querySelector("#loader"),d=document.querySelector("#gallery"),h=document.querySelector(".js-load-btn"),y="48131456-02178b54d24f02562d64ec2d5",L=new b(".gallery-link",{captionsData:"alt",captionDelay:250});let i=1,c="";const g=r=>{h.classList.toggle("hidden",!r)};u.addEventListener("submit",async r=>{if(r.preventDefault(),d.innerHTML="",c=r.currentTarget.elements.searchQuery.value.trim(),!c){a.warning({message:"Please enter a search query!",position:"topRight",timeout:3e3}),u.reset();return}f.classList.remove("hidden");try{i=1,g(!1);const{data:e}=await m(c,i,y);if(e.hits.length===0){a.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3}),u.reset();return}e.totalHits>15&&g(!0);const s=p(e.hits);d.innerHTML=s,L.refresh()}catch(e){a.error({message:`An error occurred: ${e.message}`,position:"topRight",timeout:3e3})}finally{f.classList.add("hidden")}});const S=async()=>{try{i++;const{data:r}=await m(c,i,y),e=p(r.hits);d.insertAdjacentHTML("beforeend",e),L.refresh(),r.hits.length<15||i*15>=r.totalHits?(g(!1),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3})):window.scrollBy({top:document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height*2,behavior:"smooth"})}catch(r){a.error({message:`An error occurred while loading images: ${r.message}`,position:"topRight",timeout:3e3})}};h.addEventListener("click",S);
//# sourceMappingURL=index.js.map
